### ISSUE TITLE
setup.cfg in version 0.3 wrongly mentions setuptools in install_requires?

### ISSUE THREAD

**Issue by jsmolic** [Kozea/cssselect2#18]
cssselect2-0.3 version does not seem to be using setuptools at runtime, but it's mentioned in `install_requires` in `setup.cfg`

**Comment by liZe** [comment]
Hi!

> cssselect2-0.3 version does not seem to be using setuptools at runtime, but it's mentioned in `install_requires` in `setup.cfg`

It was actually needed for the installation, I’m not sure that having it in `install_requires` is needed, so you’re probably right.

By the way, the current master branch doesn’t use setuptools anymore, I think that we can close this issue as it will be solved when the next version is released. What do you think?

**Comment by jsmolic** [comment]
Great, thanks. I'll close the issue then!
