### ISSUE TITLE
:is pseudo class support

### ISSUE THREAD

**Issue by msathis** [Kozea/cssselect2#23]
Thanks for the great library. Can we add support for :is pseudo class?

https://developer.mozilla.org/en-US/docs/Web/CSS/:is

**Comment by liZe** [comment]
Hello @msathis!

`:is()` is supported in #24, don’t hesitate to test and give feedback!

**Comment by msathis** [comment]
@liZe Just tried it out today. It was working really well 💯. Thanks for the quick & great work. ❤️ 🚀
