### ISSUE TITLE
Relative imports in __init__.py don't work with flit

### ISSUE THREAD

**Issue by taut-and-yare** [Kozea/cssselect2#26]
See the relevant [flit issue](https://github.com/pypa/flit/issues/530) giving an error:

```
35.67         from .compiler import compile_selector_list  # noqa
35.67     ModuleNotFoundError: No module named 'flit_core.dummy'
```

**Comment by liZe** [comment]
Hello, and thanks for the bug report.

That’s a bug in flit that will be fixed soon, there’s nothing we can do here about this.
